
FROM gradle:7.6-jdk17 AS build

WORKDIR /app

# copy full project 
COPY . .

# build application
WORKDIR /app
RUN gradle :backend:build -x test

# runtime stage
FROM openjdk:17-slim

WORKDIR /app

# copy built JAR file from build stage
COPY --from=build /app/backend/build/libs/backend-*.jar app.jar

# set startup command
ENTRYPOINT ["java", "-jar", "app.jar"]

# expose port app uses
EXPOSE 8080